import { useMemo } from 'react';
import axios from 'axios';
import { format } from 'date-fns';
import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import type { GetEventResponse, GetEventsResponse } from '~/@types';

type Props = {
  events: GetEventsResponse;
};

export default function Home({ events }: Props) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ul className="my-4 mx-2 xs:mx-1 sm:mx-0 grid grid-cols-1 lg:grid-cols-2 2xl:grid-cols-3 gap-10 sm:gap-20 2xl:gap-24 transition-gap">
        {events.map((event) => (
          <EventItem key={event.id} {...event} />
        ))}
      </ul>
    </>
  );
}

const EventItem = ({ id, image, name, place, dates }: GetEventResponse) => {
  const date = useMemo(() => {
    const formatStr = 'yyyy.MM.dd';
    const startDate = new Date(dates[0].startTime);
    const endDate = new Date(dates[dates.length - 1].endTime);
    return `${format(startDate, formatStr)} ~ ${format(endDate, formatStr)}`;
  }, [dates]);

  return (
    <li className="relative py-3">
      <Link href={`/events/${id}`}>
        <a>
          <div className="absolute inset-0 bg-gradient-to-r from-purple-400 to-sky-500 shadow-md transform -rotate-4 sm:-rotate-6 rounded-3xl"></div>
          <div className="relative bg-white shadow-md overflow-hidden rounded-3xl transition-transform transform hover:scale-110">
            <div>
              <div className="relative transition-height duration-300 h-52 xs:h-60 sm:h-96">
                <Image
                  src={image || ''}
                  alt=""
                  layout="fill"
                  objectFit="cover"
                  quality={50}
                  priority
                />
              </div>
              <div className="m-5 sm:m-6">
                <h2 className="font-bold text-xl sm:text-2xl mb-1 sm:mb-2">
                  {name}
                </h2>
                <div className="text-gray-400 text-sm sm:text-base mb-1">
                  {date}
                </div>
                <div className="text-gray-600 text-sm sm:text-base">
                  {place.name}
                </div>
              </div>
            </div>
          </div>
        </a>
      </Link>
    </li>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const { data: events } = await axios.get<GetEventsResponse>(
    'http://localhost:3000/api/events',
  );
  return {
    props: {
      events,
    },
  };
};
