import { TabList, Tabs } from '@reach/tabs';
import { GetServerSideProps } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { dehydrate, QueryClient } from 'react-query';
import EventForm from '~/components/admin/EventForm';
import EventList from '~/components/admin/EventList';
import { Tab, TabPanel, TabPanels } from '~/components/admin/Tab';
import { getEvents } from '~/helpers/api';

export default function EventsAdmin() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Tabs>
        <TabList className="mb-8">
          <Tab>행사 등록</Tab>
          <Tab>행사 수정</Tab>
        </TabList>
        <TabPanels>
          <TabPanel>
            <EventForm />
          </TabPanel>
          <TabPanel>
            <EventList />
            <EventForm edit />
          </TabPanel>
        </TabPanels>
      </Tabs>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  if (!session?.isAdmin) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  const queryClient = new QueryClient();
  await queryClient.prefetchQuery('events', getEvents);
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
