import { GetServerSideProps } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';

type Props = {
  foo: string;
};

export default function Admin(props: Props) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AddEventForm />
    </>
  );
}

function AddEventForm() {
  return (
    <section>
      <h2 className="text-2xl font-medium mb-4">행사 등록</h2>
      <div>
        <form></form>
      </div>
    </section>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  if (!session?.isAdmin) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
