import { GetServerSideProps } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';

type Props = {
  foo: string;
};

export default function Admin(props: Props) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      Hello Admin
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  if (!session?.isAdmin) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
