import Head from 'next/head';

type Props = {
  foo: string;
};

export default function ShopsAdmin(props: Props) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
}
